# SPDX-License-Identifier: MIT
version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  labels:
  - dependabot
  rebase-strategy: auto
  groups:
    actions-minor:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
