# SPDX-License-Identifier: MIT
name: Hadolint

on:
  workflow_call:
    inputs:
      args:
        description: 'The hadolint args. Default: `hadolint --format tty Dockerfile`'
        required: false
        default: 'hadolint --format tty Dockerfile'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: hadolint
      uses: 'docker://hadolint/hadolint:latest'
      with:
        args: '${{ inputs.args }}'
